export const cities = [
  // United States - Major Cities
  "New York, NY, USA",
  "Los Angeles, CA, USA",
  "Chicago, IL, USA",
  "Houston, TX, USA",
  "Phoenix, AZ, USA",
  "Philadelphia, PA, USA",
  "San Antonio, TX, USA",
  "San Diego, CA, USA",
  "Dallas, TX, USA",
  "San Jose, CA, USA",
  "Austin, TX, USA",
  "Jacksonville, FL, USA",
  "Fort Worth, TX, USA",
  "Columbus, OH, USA",
  "Charlotte, NC, USA",
  "San Francisco, CA, USA",
  "Indianapolis, IN, USA",
  "Seattle, WA, USA",
  "Denver, CO, USA",
  "Washington, DC, USA",
  "Boston, MA, USA",
  "El Paso, TX, USA",
  "Nashville, TN, USA",
  "Detroit, MI, USA",
  "Oklahoma City, OK, USA",
  "Portland, OR, USA",
  "Las Vegas, NV, USA",
  "Memphis, TN, USA",
  "Louisville, KY, USA",
  "Baltimore, MD, USA",
  "Milwaukee, WI, USA",
  "Albuquerque, NM, USA",
  "Tucson, AZ, USA",
  "Fresno, CA, USA",
  "Sacramento, CA, USA",
  "Kansas City, MO, USA",
  "Mesa, AZ, USA",
  "Atlanta, GA, USA",
  "Omaha, NE, USA",
  "Colorado Springs, CO, USA",
  "Raleigh, NC, USA",
  "Miami, FL, USA",
  "Long Beach, CA, USA",
  "Virginia Beach, VA, USA",
  "Oakland, CA, USA",
  "Minneapolis, MN, USA",
  "Tampa, FL, USA",
  "Tulsa, OK, USA",
  "Arlington, TX, USA",
  "New Orleans, LA, USA",
  "Wichita, KS, USA",
  "Cleveland, OH, USA",
  "Bakersfield, CA, USA",
  "Aurora, CO, USA",
  "Anaheim, CA, USA",
  "Honolulu, HI, USA",
  "Santa Ana, CA, USA",
  "Riverside, CA, USA",
  "Corpus Christi, TX, USA",
  "Lexington, KY, USA",
  "Stockton, CA, USA",
  "Henderson, NV, USA",
  "Saint Paul, MN, USA",
  "St. Louis, MO, USA",
  "Cincinnati, OH, USA",
  "Pittsburgh, PA, USA",
  "Greensboro, NC, USA",
  "Anchorage, AK, USA",
  "Plano, TX, USA",
  "Lincoln, NE, USA",
  "Orlando, FL, USA",
  "Irvine, CA, USA",
  "Newark, NJ, USA",
  "Durham, NC, USA",
  "Chula Vista, CA, USA",
  "Toledo, OH, USA",
  "Fort Wayne, IN, USA",
  "St. Petersburg, FL, USA",
  "Laredo, TX, USA",
  "Jersey City, NJ, USA",
  "Chandler, AZ, USA",
  "Madison, WI, USA",
  "Lubbock, TX, USA",
  "Norfolk, VA, USA",
  "Baton Rouge, LA, USA",
  "Reno, NV, USA",
  "Buffalo, NY, USA",
  "Gilbert, AZ, USA",
  "Glendale, AZ, USA",
  "North Las Vegas, NV, USA",
  "Winston-Salem, NC, USA",
  "Chesapeake, VA, USA",
  "Scottsdale, AZ, USA",
  "San Bernardino, CA, USA",
  "Irving, TX, USA",
  "Fremont, CA, USA",
  "Boise, ID, USA",
  "Richmond, VA, USA",
  "Des Moines, IA, USA",
  "Spokane, WA, USA",
  "Yonkers, NY, USA",
  "Akron, OH, USA",
  "Huntington Beach, CA, USA",
  "Little Rock, AR, USA",
  "Augusta, GA, USA",
  "Amarillo, TX, USA",
  "Glendale, CA, USA",
  "Mobile, AL, USA",
  "Grand Rapids, MI, USA",
  "Salt Lake City, UT, USA",
  "Tallahassee, FL, USA",
  "Huntsville, AL, USA",
  "Grand Prairie, TX, USA",
  "Knoxville, TN, USA",
  "Worcester, MA, USA",
  "Newport News, VA, USA",
  "Brownsville, TX, USA",
  "Overland Park, KS, USA",
  "Santa Clarita, CA, USA",
  "Providence, RI, USA",
  "Garden Grove, CA, USA",
  "Chattanooga, TN, USA",
  "Oceanside, CA, USA",
  "Jackson, MS, USA",
  "Fort Lauderdale, FL, USA",
  "Santa Rosa, CA, USA",
  "Rancho Cucamonga, CA, USA",
  "Port St. Lucie, FL, USA",
  "Tempe, AZ, USA",
  "Ontario, CA, USA",
  "Vancouver, WA, USA",
  "Cape Coral, FL, USA",
  "Sioux Falls, SD, USA",
  "Springfield, MO, USA",
  "Peoria, AZ, USA",
  "Pembroke Pines, FL, USA",
  "Elk Grove, CA, USA",
  "Salem, OR, USA",
  "Lancaster, CA, USA",
  "Corona, CA, USA",
  "Eugene, OR, USA",
  "Palmdale, CA, USA",
  "Salinas, CA, USA",
  "Springfield, MA, USA",
  "Pasadena, CA, USA",
  "Fort Collins, CO, USA",
  "Hayward, CA, USA",
  "Pomona, CA, USA",
  "Cary, NC, USA",
  "Rockford, IL, USA",
  "Alexandria, VA, USA",
  "Escondido, CA, USA",
  "McKinney, TX, USA",
  "Kansas City, KS, USA",
  "Joliet, IL, USA",
  "Sunnyvale, CA, USA",
  "Torrance, CA, USA",
  "Bridgeport, CT, USA",
  "Lakewood, CO, USA",
  "Hollywood, FL, USA",
  "Paterson, NJ, USA",
  "Naperville, IL, USA",
  "Syracuse, NY, USA",
  "Mesquite, TX, USA",
  "Dayton, OH, USA",
  "Savannah, GA, USA",
  "Clarksville, TN, USA",
  "Orange, CA, USA",
  "Pasadena, TX, USA",
  "Fullerton, CA, USA",
  "Killeen, TX, USA",
  "Frisco, TX, USA",
  "Hampton, VA, USA",
  "McAllen, TX, USA",
  "Warren, MI, USA",
  "Bellevue, WA, USA",
  "West Valley City, UT, USA",
  "Columbia, MO, USA",
  "Olathe, KS, USA",
  "Sterling Heights, MI, USA",
  "New Haven, CT, USA",
  "Miramar, FL, USA",
  "Waco, TX, USA",
  "Thousand Oaks, CA, USA",
  "Cedar Rapids, IA, USA",
  "Charleston, SC, USA",
  "Visalia, CA, USA",
  "Topeka, KS, USA",
  "Elizabeth, NJ, USA",
  "Gainesville, FL, USA",
  "Thornton, CO, USA",
  "Roseville, CA, USA",
  "Carrollton, TX, USA",
  "Coral Springs, FL, USA",
  "Stamford, CT, USA",
  "Simi Valley, CA, USA",
  "Concord, CA, USA",
  "Hartford, CT, USA",
  "Kent, WA, USA",
  "Lafayette, LA, USA",
  "Midland, TX, USA",
  "Surprise, AZ, USA",
  "Denton, TX, USA",
  "Victorville, CA, USA",
  "Evansville, IN, USA",
  "Santa Clara, CA, USA",
  "Abilene, TX, USA",
  "Athens, GA, USA",
  "Vallejo, CA, USA",
  "Allentown, PA, USA",
  "Norman, OK, USA",
  "Beaumont, TX, USA",
  "Independence, MO, USA",
  "Murfreesboro, TN, USA",
  "Ann Arbor, MI, USA",
  "Fargo, ND, USA",
  "Wilmington, NC, USA",
  "Golden, CO, USA",
  "Columbia, SC, USA",
  "Carmel, IN, USA",
  "Meridian, ID, USA",
  
  // Canada - Major Cities
  "Toronto, ON, Canada",
  "Montreal, QC, Canada",
  "Vancouver, BC, Canada",
  "Calgary, AB, Canada",
  "Edmonton, AB, Canada",
  "Ottawa, ON, Canada",
  "Winnipeg, MB, Canada",
  "Quebec City, QC, Canada",
  "Hamilton, ON, Canada",
  "Kitchener, ON, Canada",
  "London, ON, Canada",
  "Victoria, BC, Canada",
  "Halifax, NS, Canada",
  "Oshawa, ON, Canada",
  "Windsor, ON, Canada",
  "Saskatoon, SK, Canada",
  "St. Catharines, ON, Canada",
  "Regina, SK, Canada",
  "Sherbrooke, QC, Canada",
  "Kelowna, BC, Canada",
  "Barrie, ON, Canada",
  "Abbotsford, BC, Canada",
  "Coquitlam, BC, Canada",
  "Trois-Rivières, QC, Canada",
  "Guelph, ON, Canada",
  "Cambridge, ON, Canada",
  "Whitby, ON, Canada",
  "Ajax, ON, Canada",
  "Langley, BC, Canada",
  "Saanich, BC, Canada",
  "Milton, ON, Canada",
  "St. John's, NL, Canada",
  "Moncton, NB, Canada",
  "Kamloops, BC, Canada",
  "Brampton, ON, Canada",
  "Mississauga, ON, Canada",
  "Markham, ON, Canada",
  "Vaughan, ON, Canada",
  "Richmond Hill, ON, Canada",
  "Oakville, ON, Canada",
  "Burlington, ON, Canada",
  "Richmond, BC, Canada",
  "Burnaby, BC, Canada",
  "Surrey, BC, Canada",
  "Laval, QC, Canada",
  "Longueuil, QC, Canada",
  
  // United Kingdom - Major Cities
  "London, England, UK",
  "Birmingham, England, UK",
  "Manchester, England, UK",
  "Glasgow, Scotland, UK",
  "Liverpool, England, UK",
  "Leeds, England, UK",
  "Sheffield, England, UK",
  "Edinburgh, Scotland, UK",
  "Bristol, England, UK",
  "Cardiff, Wales, UK",
  "Leicester, England, UK",
  "Coventry, England, UK",
  "Bradford, England, UK",
  "Belfast, Northern Ireland, UK",
  "Nottingham, England, UK",
  "Kingston upon Hull, England, UK",
  "Newcastle upon Tyne, England, UK",
  "Stoke-on-Trent, England, UK",
  "Southampton, England, UK",
  "Derby, England, UK",
  "Portsmouth, England, UK",
  "Brighton, England, UK",
  "Plymouth, England, UK",
  "Northampton, England, UK",
  "Reading, England, UK",
  "Luton, England, UK",
  "Wolverhampton, England, UK",
  "Bolton, England, UK",
  "Bournemouth, England, UK",
  "Norwich, England, UK",
  "Swindon, England, UK",
  "Swansea, Wales, UK",
  "Southend-on-Sea, England, UK",
  "Middlesbrough, England, UK",
  "Peterborough, England, UK",
  "Cambridge, England, UK",
  "Oxford, England, UK",
  "Blackpool, England, UK",
  "Ipswich, England, UK",
  "York, England, UK",
  "West Bromwich, England, UK",
  "Slough, England, UK",
  "Gloucester, England, UK",
  "Watford, England, UK",
  "Rotherham, England, UK",
  "Newport, Wales, UK",
  "Exeter, England, UK",
  "Scunthorpe, England, UK",
  "Hemel Hempstead, England, UK",
  
  // Australia - Major Cities
  "Sydney, NSW, Australia",
  "Melbourne, VIC, Australia",
  "Brisbane, QLD, Australia",
  "Perth, WA, Australia",
  "Adelaide, SA, Australia",
  "Gold Coast, QLD, Australia",
  "Newcastle, NSW, Australia",
  "Canberra, ACT, Australia",
  "Sunshine Coast, QLD, Australia",
  "Wollongong, NSW, Australia",
  "Hobart, TAS, Australia",
  "Geelong, VIC, Australia",
  "Townsville, QLD, Australia",
  "Cairns, QLD, Australia",
  "Darwin, NT, Australia",
  "Toowoomba, QLD, Australia",
  "Ballarat, VIC, Australia",
  "Bendigo, VIC, Australia",
  "Albury, NSW, Australia",
  "Launceston, TAS, Australia",
  "Mackay, QLD, Australia",
  "Rockhampton, QLD, Australia",
  "Bunbury, WA, Australia",
  "Bundaberg, QLD, Australia",
  "Coffs Harbour, NSW, Australia",
  "Wagga Wagga, NSW, Australia",
  "Hervey Bay, QLD, Australia",
  "Mildura, VIC, Australia",
  "Shepparton, VIC, Australia",
  "Port Macquarie, NSW, Australia",
  
  // Remote/Virtual Options
  "Remote",
  "Remote - USA",
  "Remote - Canada",
  "Remote - UK",
  "Remote - Australia",
  "Remote - Europe",
  "Remote - Global",
  "Work from Home",
  "Virtual",
  "Distributed",
  "Hybrid",
  "Multiple Locations"
]

export function searchCities(query: string): string[] {
  if (!query || query.length < 2) return []
  
  const lowercaseQuery = query.toLowerCase()
  return cities
    .filter(city => city.toLowerCase().includes(lowercaseQuery))
    .slice(0, 10) // Limit to 10 results for performance
} 